#ifndef ASSETS_H
#define ASSETS_H

enum ASSETS_ANIMATION_IDX {
    ASSET_NO_ANIMATION,
    ASSET_HERO_ANIMATION,
    ASSET_HERO_TEST,
    ASSET_ANIMATION_ALL
};

enum ASSETS_LIGHTSOURCES_IDX {
    ASSET_LIGHTER_LIGHTSOURCE,
    ASSET_LANTERN_LIGHTSOURCE,
    ASSET_LIGHTSOURCE_ALL
};

enum ASSETS_GRADIENT_IDX {
    ASSET_GRADIENT_CIRCULAR,
    ASSET_GRADIENT_ALL
};

enum ASSETS_SPRITE_IDX {
    ASSET_SPRITE_HERO,
    ASSET_SPRITE_TEST,
    ASSET_SPRITE_LIGHTER,
    ASSET_SPRITE_ALL
};

enum ASSETS_WOBBLE_IDX {
    ASSET_WOBBLE_NO,
    ASSET_WOBBLE_STABLE,
    ASSET_WOBBLE_WALKING,
    ASSET_WOBBLE_ALL
};

enum ASSETS_LEVEL_IDX {
    ASSET_LEVEL_SAMPLE,
    ASSET_LEVEL_ALL
};

#endif
