#ifndef ASSETS_H
#define ASSETS_H

// TODO: this will be deleted after implementing data library in new way
enum ASSETS_LIGHTSOURCES_IDX {
    ASSET_LIGHTSOURCE_LIGHTER,
    ASSET_LIGHTSOURCE_WALLLIGHT,
    ASSET_LIGHTSOURCE_NO,
    ASSET_LIGHTSOURCE_ALL
};

enum ASSETS_SPRITE_IDX {
    ASSET_SPRITE_HERO,
    ASSET_SPRITE_TEST,
    ASSET_SPRITE_LIGHTER,
    ASSET_SPRITE_WALLLIGHT,
    ASSET_SPRITE_ALL
};
#endif
