#include "library.h"
#include "../assets.h"
#include "../primitives.h"
#include "../animation.h"

entity_blueprint_t* entity_library[ENTITY_ALL] = {NULL};


// these animations should propably be generated by some algorithm, not by hand, but this will be a
// very far step in the game editor

entity_blueprint_t entity_blueprint_hero = {
    ENTITY_HERO, // id
    MOVABLE | APPLY_COLLISION | CONTROLABLE | STATEABLE | APPLY_FRICTION | ANIMATIABLE, // flags
    HANDLE_TYPE_NO,  // handle_type
    HANDLE_TYPE_NO,  // light_emmit_pt
    ASSET_SPRITE_HERO, // texture_id
    ASSET_LIGHTSOURCE_NO, // lighsource
    ENTITY_LIGHTER,  // hold id
    STANDING,  // starting_state
    {
        NULL,
        4,
        {
            { // WALKING
                2, // len
                {
                    {
                        (render_img_t) { 0.0, 0.0, 9.0/27.0, 20.0/40.0},
                        (SDL_Rect)     { 0,   0,   9,        20 },
                        { (SDL_Rect) {0, 0, 9, 20} },
                        9, 10, 1, 20
                    },
                    {
                        (render_img_t) { 9.0/27.0, 0.0, 9.0/27.0, 20.0/40.0 },
                        (SDL_Rect)     { 9,         0,  9,        20 },
                        { (SDL_Rect) {0, 0, 9, 20} },
                        9, 10, 1, 20
                    },
                }
            },

            { // STANDING
                2, // len
                {
                    {
                        (render_img_t) { 0.0, 20.0/40.0, 9.0/27.0, 20.0/40.0},
                        (SDL_Rect)     { 0,   20,        9,        20 },
                        { (SDL_Rect) {0, 0, 9, 20} },
                        9, 10, 1, 5
                    },
                    {
                        (render_img_t) { 9.0/27.0, 20.0/40.0, 9.0/27.0, 20.0/40.0},
                        (SDL_Rect)     { 9,        20,        9,        20 },
                        { (SDL_Rect) {0, 0, 9, 20} },
                        9, 10, 1, 5
                    },
                }
            },
            { // JUMPING
                1, // len
                {
                    {
                        (render_img_t) { 18.0/27.0, 0, 9.0/27.0, 20.0/40.0},
                        (SDL_Rect)     { 18,        0, 9,        20 },
                        { (SDL_Rect) {0, 0, 9, 20} },
                        9, 10, 1, 0
                    },
                }
            },

            { // FALLING
                1, // len
                {
                    {
                        (render_img_t) { 18.0/27.0, 20.0/40.0, 9.0/27.0, 20.0/40.0},
                        (SDL_Rect)     { 18,        20,        9,        20 },
                        { (SDL_Rect) {0, 0, 9, 20} },
                        9, 10, 1, 0
                    },
                }
            }
        }
    }
};

entity_blueprint_t entity_blueprint_lighter = {
    ENTITY_LIGHTER,
    HOLDABLE | EMMIT_LIGHT,
    HANDLE_MIDDLE_UP,
    HANDLE_FRONT_MIDDLE,
    ASSET_SPRITE_LIGHTER,
    ASSET_LIGHTSOURCE_LIGHTER,
    ENTITY_NO,
    NOTHING,
    { NULL }
};

entity_blueprint_t entity_blueprint_walllight = {
    ENTITY_WALLLIGHT,
    HANDLE_MIDDLE_MIDDLE,
    HANDLE_MIDDLE_MIDDLE,
    ASSET_NO_ANIMATION,
    ASSET_SPRITE_WALLLIGHT,
    ASSET_LIGHTSOURCE_WALLLIGHT,
    ENTITY_NO,
    NOTHING,
    { NULL }
};

void LIB_create_entity_library(
) {
    entity_library[ENTITY_HERO] = &entity_blueprint_hero;
    entity_library[ENTITY_LIGHTER] = &entity_blueprint_lighter;
    entity_library[ENTITY_WALLLIGHT] = &entity_blueprint_walllight ;
}
